services:
  cc25-backend:
    image: ghcr.io/manangandhi1810/cc25-backend:latest
    container_name: cc-25-backend
    restart: unless-stopped
    ports:
      - 8000:8080/tcp
    environment:
      MONGO_URI: <MONGO_URI>
      SECRET_KEY: <SECRET_KEY>
      GOOGLE_API_KEY: <GGOGLE_API_KEY>
      SERAPI_KEY: <SERAPI_KEY>
      DEBUG: False