services:
  cc25-backend:
    image: ghcr.io/manangandhi1810/cc25-backend:latest
    container_name: cc-25-backend
    restart: unless-stopped
    ports:
      - 8080:8080/tcp
    env_file:
      - .env

  cc25-frontend:
    image: ghcr.io/manangandhi1810/cc25-frontend:latest
    container_name: cc25-frontend
    restart: unless-stopped
    ports:
      - 3000:3000/tcp
    depends_on:
      - cc25-backend
    env_file:
      - .env